import { defineStore } from 'pinia'
import { ref } from 'vue'

export const DEFAULT_TEMPERATURE = 'от: -20С; -40С до: +40С; +50С; +60С';
export const DEFAULT_PLACEMENT = 'У1 (на улице), У2 (под навесом), У3 (в помещении)';
export const DEFAULT_EXECUTION = 'общепромышленное, пожаробезопасное, взрывозащищенное';

interface Produce {

    id:          number
    url:         string   // адрес
    name:        string   // имя продукции
    load:        string   // грузоподъемность (т)
    departure:   string   // вылет стрелы (м)
    drive:       string   // тип привода
    lifting:     string   // высота подъема (м)
    mode:        string   // режим работы
    execution:   string   // DEFAULT_EXECUTION
    temperature: string   // DEFAULT_TEMPERATUR
    placement:   string   // DEFAULT_PLACEMENT
    speed:       string   // скорость поворота стрелы крана (м/мин)
    stability:   string   // сейсмоустойчивость
    management:  string   // способ управления краном
    motor:       string   // мотор-редукторы крана
    components:  string   // электрокомпоненты в составе крана
    certificate: string   // имя сетификата
    typesection: string   // тип сечения
    class:       string   // класс пожароопасности
    length:      string   // ширина пролет
    movements:   string   // скорость передвижения (м/мин.)
    image_a:     string   // изображение
    image_b:     string   // изображение
    image_c:     string   // изображение
    climate:     string   // климатическое исполнение (варианты по согласованному требованию)
    rotation:    string   // способ управления поворотом консоли
    hoist:       string   // способ управления электрической талью
    current:     string   // электрический ток
    trials:      string   // масса испытательных грузов при статических испытаниях - при динамических испытаниях
    options:     string   // дополнительные опции
    seo_descrip: string 
    seo_keyword: string
    html_a:      string
    html_b:      string

}

export const useProduceStore = defineStore('cranes', () => {
    const cranes = ref<Produce[]>([
        {
            id: 1,
            url: 'konsole-electric',
            name: 'Кран консольный электрический',
            load: 'от 0,25 до 10',
            length: '',
            class: '',
            departure: 'от 2 до 7',
            drive: 'электрический',
            rotation: '',
            hoist: '',
            lifting: 'до 10',
            typesection: '',
            mode: 'от А1 до А5',
            climate: 'У, УХЛ, ХЛ',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: '',
            speed: '0,25 до 1',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'konsole-electric.jpg',
            image_b:'konsole-electric.jpg',
            image_c:'konsole-electric.jpg',
            options: '',
            certificate: 'sertificate-console.pdf',
            seo_descrip: 'Купить кран консольный электрический грузоподъемностью до 10 т. Надежное оборудование, доставка по РФ, выгодные цены от производителя.',
            seo_keyword: 'кран консольный, кран консольный поворотный, электрический кран, грузоподъемное оборудование, кран на колонне',
            html_a:'',
            html_b:''
        },
        {
            id: 2,
            url: 'konsole-mech', 
            name: 'Кран консольный ручной',
            load: 'от 0,25 до 10',
            length: '',
            class: '',
            departure: 'от 2 до 7',
            drive: 'ручной',
            rotation: '',
            hoist: '',
            lifting: 'до 10',
            typesection: '',
            mode: 'от А1 до А5',
            climate: 'У, УХЛ, ХЛ',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: '',
            speed: '',
            stability: 'до 9 баллов',
            management: 'ручной с пола',
            motor: 'Болгария, Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'konsole-mech.jpg',
            image_b:'konsole-mech-b.avif',
            image_c:'konsole-mech.jpg',
            options: '',
            certificate: 'sertificate-console.pdf',
            seo_descrip: 'Купить кран консольный ручной грузоподъемностью до 10 т. Надежное оборудование, доставка по РФ, выгодные цены от производителя.',
            seo_keyword: 'кран консольный ручной, кран консольный поворотный, грузоподъемное оборудование, кран на колонне',
            html_a:'<h2>Описание</h2><p>Кран консольный с ручным поворотом консоли — это компактная грузоподъемная установка, состоящая из вертикальной опоры (колонны) и поворотной горизонтальной стрелы (консоли). На стреле размещается ручная таль, которая перемещается вдоль балки, обеспечивая точное позиционирование груза.</p><p>Кран монтируется непосредственно у рабочей зоны (станка, сборочного стенда, ремонтной ямы) и позволяет одному оператору выполнять полный цикл грузоподъемных операций: захват, подъем, поворот, горизонтальное перемещение и опускание груза. Привод — ручной, что обеспечивает автономность, плавность хода и минимальные эксплуатационные затраты.</p>',
            html_b:'<h2>Комплект</h2><p>&mdash; стрела (консоль) крана — 1 шт.;</p><p>&mdash; таль (при поставке в комплекте с талью) – 1 шт.;</p><p>&mdash; прочие части (перечень составных частей зависит от комплектации и набора опций заказанного Вами крана и может отличаться от приведенного в данном разделе сайта);</p><p>&mdash; документация на кран (паспорт, руководство по эксплуатации и монтажу крана, паспорта и инструкции на отдельные узлы крана, изготовленные на других предприятиях и поставляемые с данным краном, упаковочный лист, товарно-транспортная накладная).</p>'
        },
        {
            id: 3,
            url: 'konsole-wall',
            name: 'Кран консольный настенный',
            load: '0,25 до 3,2',
            length: '',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: 'электрический, ручной',
            hoist: 'Электрический от пульта',
            lifting: '',
            typesection: '',
            mode: 'от А1 до А5',
            climate: 'У, УХЛ, ХЛ',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '380В, 50Гц, трехфазный',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: '',
            speed: '',
            stability: '',
            management: '',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'konsole-wall.jpg',
            image_b:'konsole-wall.jpg',
            image_c:'konsole-wall.jpg',
            options: '',
            certificate: 'sertificate-console.pdf',
            seo_descrip: 'Купить кран консольный настенный грузоподъемностью до 3,2 т. Надежное оборудование, доставка по РФ, выгодные цены от производителя.',
            seo_keyword: 'кран консольный ручной, кран консольный поворотный, грузоподъемное оборудование, кран консольный настенный',
            html_a:'',
            html_b:''
        },
        {
            id: 4,
            url: 'single-girder',
            name: 'Кран опорный однобалочный',
            load: 'от 0,5 до 20',
            length: 'от 3 до 35',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: 'электрический, ручной',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр, ферма',
            mode: 'от А1 до А5',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: 'от 20 до 100',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина', 
            motor: 'Болгария, Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'single-girder.jpg',
            image_b:'single-girder.jpg',
            image_c:'single-girder.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: 'Опорный однобалочный кран от завода-изготовителя ПК Крантехмаш: проектирование, производство, монтаж и сервисное обслуживание. Надежные решения для ваших задач. Закажите расчёт под ваши задачи. Доставка по всей РФ.',
            seo_keyword: 'кран однобалочный опорный, кран мостовой, кран-балка опорная',
            html_a:'',
            html_b:''
        },
        {
            id: 5,
            url: 'dubble-girder',
            name: 'Кран опорный двухбалочный',
            load: 'от 0,5 до 50',
            length: 'от 3 до 40',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: 'электрический',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр, ферма',
            mode: 'от А1 до А8',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: 'от 10 до 120',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Болгария, Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'dubble-girder.jpg',
            image_b:'dubble-girder.jpg',
            image_c:'dubble-girder.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: 'Опорный двухбалочный кран под ключ: разработка в собственном конструкторском бюро, изготовление, монтаж и сервисное обслуживание. Грузоподъёмность до 50 тонн. Получите рассчёт стоимости сегодня.',
            seo_keyword: 'двухбалочный кран, опорный двухбалочный, кран-балка двухбалочная',
            html_a:'',
            html_b:''
        },
        {
            id: 6,
            url: 'suspended-single-span',
            name: 'Кран подвесной однопролетный',
            load: 'от 0,5 до 16',
            length: 'от 3 до 15',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр',
            mode: 'от А1 до А5',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: 'от 5 до 32',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Болгария, Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'suspended-dubble-span.jpg',
            image_b:'suspended-dubble-span.jpg',
            image_c:'suspended-dubble-span.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: 'Подвесной однопролётный кран от завода ПК Крантехмаш: проектирование под ваши параметры, монтаж на вашем объекте. Оптимальное решение для ограниченного пространства. Получить рассчит стоимость за 1 день.',
            seo_keyword: 'однопролётный кран, подвесной однопролётный, кран подвесной',
            html_a:'',
            html_b:''
        },
        {
            id: 7,
            url: 'suspended-dubble-span',
            name: 'Кран подвесной двухпролетный',
            load: 'от 0,5 до 16',
            length: 'от 3 до 15',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр',
            mode: 'от А1 до А5',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: 'от 5 до 32',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'suspended-single-span.jpg',
            image_b:'suspended-single-span.jpg',
            image_c:'suspended-single-span.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: 'Подвесной двухпролётный кран под ваши параметры: собственное конструкторское бюро, изготовление, монтаж на вашем предприятии. Грузоподъёмность до 16 тонн. Доставка по всей России. Закажите консультацию.',
            seo_keyword: 'подвесной двухпролётный, подвесной кран, двухпролётный кран',
            html_a:'',
            html_b:''
        },
        {
            id: 8,
            url: 'gantry',
            name: 'Козловые краны',
            load: 'от 1 до 20',
            length: 'до 30',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'до 14',
            typesection: 'коробчатый, двутавр',
            mode: 'от А1 до А6',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: '',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Италия, Германия, Китай, Болгария',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'gantry.jpg',
            image_b:'gantry.jpg',
            image_c:'gantry.jpg',
            options: '',
            certificate: '',
            seo_descrip: 'Козловые краны любой сложности до 20 тонн: проектирование, производство, ввод в эксплуатацию. Для портов, складов, производств и инных задач. Гарантия на продукцию. Сервисное обслуживание.',
            seo_keyword: 'козловой кран, козловой',
            html_a:'',
            html_b:''
        },
        {
            id: 9,
            url: 'mobile-transshipment',
            name: 'Мобильное перегрузочное устройство',
            load: 'до 5',
            length: 'от 1 до 5,5',
            class: '',
            departure: '',
            drive: 'электрический',
            rotation: '',
            hoist: '',
            lifting: 'до 1,5',
            typesection: '',
            mode: '',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: '',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт',
            motor: 'Италия, Германия, Китай, Болгария',
            components: 'Италия, Германия, Россия, Китай',
            image_a:'mobile-transshipment.jpg',
            image_b:'mobile-transshipment.jpg',
            image_c:'mobile-transshipment.jpg',
            options: '',
            certificate: '',
            seo_descrip: 'Мобильные перегрузочные устройства от ПК Крантехмаш: быстромонтируемые, маневренные, под индивидуальную нагрузку. Максимальная грузоподъемность 5 тонн. Узнайте стоимость и срок изготовления. Доставим в любой город.',
            seo_keyword: 'мобильное перегрузочное устройство, перегрузочное устройство',
            html_a:'',
            html_b:''
        },
        {
            id: 10,
            url: 'trolleys-support',
            name: 'Концевые балки к опорному крану',
            load: 'от 1 до 50',
            length: 'от 3 до 40',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: '',
            typesection: '',
            mode: 'от А1 до А7',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: 'от 1 до 100',
            speed: '',
            stability: 'до 9 баллов',
            management: '',
            motor: 'Италия, Германия, Китай, Болгария',
            components: '',
            image_a:'trolleys-support.jpg',
            image_b:'trolleys-support.jpg',
            image_c:'trolleys-support.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: 'Концевые балки для опорных кранов: производство в соответствии с ГОСТ, грузоподъёмность до 50 тонн, доставка по РФ. Замена и модернизация оборудования. Закажите расчёт прочности и стоимости изготовления.',
            seo_keyword: 'концевые балки, балки к опорному, тележки к опорному, тележки к опорному крану, концевые тележки',
            html_a:'',
            html_b:''
        },
        {
            id: 11,
            url: 'trolleys-suspension',
            name: 'Концевые балки к подвесному крану',
            load: 'от 1 до 10',
            length: 'от 3 до 24',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: '',
            typesection: '',
            mode: 'от А1 до А7',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '380В, 50Гц, трехфазный',
            trials: '1,25 номинальной г/п в статике, 1,1 номинальной г/п в движении',
            movements: 'от 1 до 100',
            speed: '',
            stability: 'до 9 баллов',
            management: '',
            motor: 'Италия, Германия, Китай, Болгария',
            components: '',
            image_a:'trolleys-suspension.jpg',
            image_b:'trolleys-suspension.jpg',
            image_c:'trolleys-suspension.jpg',
            options: 'радиоуправление; термозащита на электродвигателях; частотное управление; тормоз электродвигателя на передвижение крана;',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: 'Концевые балки для подвесных кранов: грузоподъёмность до 10 тонн, монтаж на вашем объекте. Сертифицированная продукция. Гарантия и обслуживание. Собственное конструкторское бюро и производство. Отправьте запрос и получить полный расчёт и консультацию.',
            seo_keyword: 'балки для подвесного, кран-балки, концевые тележки, тележки для подвесного',
            html_a:'',
            html_b:''
        }
    ])

    return {
        cranes
    }
    
})