import { defineStore } from 'pinia'
import { ref } from 'vue'

export const DEFAULT_TEMPERATURE = 'от: -20С; -40С до: +40С; +50С; +60С';
export const DEFAULT_PLACEMENT = 'У1 (на улице), У2 (под навесом), У3 (в помещении)';
export const DEFAULT_EXECUTION = 'общепромышленное, пожаробезопасное, взрывозащищенное';

interface Produce {

    id:          number
    url:         string   // адрес
    name:        string   // имя продукции
    load:        string   // грузоподъемность (т)
    departure:   string   // вылет стрелы (м)
    drive:       string   // тип привода
    lifting:     string   // высота подъема (м)
    mode:        string   // режим работы
    execution:   string   // DEFAULT_EXECUTION
    temperature: string   // DEFAULT_TEMPERATUR
    placement:   string   // DEFAULT_PLACEMENT
    speed:       string   // скорость поворота стрелы крана (м/мин)
    stability:   string   // сейсмоустойчивость
    management:  string   // способ управления краном
    motor:       string   // мотор-редукторы крана
    components:  string   // электрокомпоненты в составе крана
    certificate: string   // имя сетификата
    typesection: string   // тип сечения
    class:       string   // класс пожароопасности
    length:      string   // ширина пролет
    movements:   string   // скорость передвижения (м/мин.)
    image:       string   // изображение
    climate:     string   // климатическое исполнение (варианты по согласованному требованию)
    rotation:    string   // способ управления поворотом консоли
    hoist:       string   // способ управления электрической талью
    current:     string   // электрический ток
    trials:      string   // масса испытательных грузов при статических испытаниях - при динамических испытаниях
    options:     string   // дополнительные опции
    seo_descrip: string 
    seo_keyword: string

}

export const useProduceStore = defineStore('cranes', () => {
    const cranes = ref<Produce[]>([
        {
            id: 1,
            url: 'konsole-electric',
            name: 'Кран консольный электрический',
            load: 'от 0,25 до 10',
            length: '',
            class: '',
            departure: 'от 2 до 7',
            drive: 'электрический',
            rotation: '',
            hoist: '',
            lifting: 'до 10',
            typesection: '',
            mode: 'от А3 до А5',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: '',
            speed: '0,25 до 1',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image:'konsole-electric.jpg',
            options: '',
            certificate: 'sertificate-console.pdf',
            seo_descrip: 'Купить кран консольный электрический грузоподъемностью до 10т. Надежное оборудование, доставка по РФ, выгодные цены от производителя.',
            seo_keyword: 'кран консольный, электрический кран, грузоподъемное оборудование, кран на колонне'
        },
        {
            id: 2,
            url: 'konsole-mech',
            name: 'Кран консольный ручной',
            load: 'от 0,25 до 10',
            length: '',
            class: '',
            departure: 'от 2 до 7',
            drive: 'ручной',
            rotation: '',
            hoist: '',
            lifting: 'до 10',
            typesection: '',
            mode: 'А1',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: '',
            speed: '',
            stability: 'до 9 баллов',
            management: 'ручной с пола',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image:'konsole-mech.jpg',
            options: '',
            certificate: 'sertificate-console.pdf',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 3,
            url: 'konsole-wall',
            name: 'Кран консольный настенный',
            load: '0,25 до 3,2',
            length: '',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: 'электрический, ручной',
            hoist: 'Электрический от пульта',
            lifting: '',
            typesection: '',
            mode: 'А3',
            climate: 'У, УХЛ, ХЛ',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '380В, 50Гц, трехфазный',
            trials: '1,25 номинальной г/п 1,1 номинальной г/п',
            movements: '',
            speed: '',
            stability: '',
            management: '',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image:'konsole-wall.jpg',
            options: '',
            certificate: 'sertificate-console.pdf',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 4,
            url: 'single-girder',
            name: 'Кран опорный однобалочный',
            load: 'от 0,5 до 20',
            length: 'от 3 до 35',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр, ферма',
            mode: 'от А1 до А5',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: 'от 20 до 100',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image:'single-girder.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 5,
            url: 'dubble-girder',
            name: 'Кран опорный двухбалочный',
            load: 'от 0,5 до 50',
            length: 'от 3 до 40',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр, ферма',
            mode: 'от А1 до А8',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: 'от 10 до 120',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image:'dubble-girder.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 6,
            url: 'suspended-single-span',
            name: 'Кран подвесной однопролетный',
            load: 'от 0,5 до 16',
            length: 'от 3 до 15',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр',
            mode: 'от А1 до А5',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: 'от 5 до 32',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image:'suspended-single-span.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 7,
            url: 'suspended-dubble-span',
            name: 'Кран подвесной двухпролетный',
            load: 'от 0,5 до 16',
            length: 'от 3 до 15',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'от 6 до 52',
            typesection: 'коробчатый, двутавр',
            mode: 'от А1 до А5',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: 'от 5 до 32',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Италия, Германия, Китай',
            components: 'Италия, Германия, Россия, Китай',
            image:'suspended-dubble-span.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 8,
            url: 'gantry',
            name: 'Козловые краны',
            load: 'до 20',
            length: 'до 30',
            class: '',
            departure: '',
            drive: 'электрический, ручной',
            rotation: '',
            hoist: '',
            lifting: 'до 14',
            typesection: 'коробчатый, двутавр',
            mode: 'от А1 до А6',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: '',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт, радиоуправление, стационарная кабина',
            motor: 'Италия, Германия, Китай, Болгария',
            components: 'Италия, Германия, Россия, Китай',
            image:'gantry.jpg',
            options: '',
            certificate: '',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 9,
            url: 'mobile-transshipment',
            name: 'Мобильное перегрузочное устройство',
            load: 'до 1',
            length: 'от 1 до 5,5',
            class: '',
            departure: '',
            drive: 'электрический',
            rotation: '',
            hoist: '',
            lifting: 'до 1,5',
            typesection: '',
            mode: '',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: '',
            speed: '',
            stability: 'до 9 баллов',
            management: 'подвесной пульт',
            motor: 'Италия, Германия, Китай, Болгария',
            components: 'Италия, Германия, Россия, Китай',
            image:'mobile-transshipment.jpg',
            options: '',
            certificate: '',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 10,
            url: 'trolleys-support',
            name: 'Концевые балки к опорному крану',
            load: 'от 1 до 50',
            length: 'от 3 до 24',
            class: '',
            departure: '',
            drive: '',
            rotation: '',
            hoist: '',
            lifting: '',
            typesection: '',
            mode: 'от А1 до А7',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '',
            trials: '',
            movements: 'от 1 до 100',
            speed: '',
            stability: 'до 9 баллов',
            management: '',
            motor: '',
            components: '',
            image:'trolleys-support.jpg',
            options: '',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: '',
            seo_keyword: ''
        },
        {
            id: 11,
            url: 'trolleys-suspension',
            name: 'Концевые балки к подвесному крану',
            load: 'от 1 до 10',
            length: 'от 3 до 24',
            class: '',
            departure: '',
            drive: '',
            rotation: '',
            hoist: '',
            lifting: '',
            typesection: '',
            mode: 'от А1 до А7',
            climate: '',
            execution: DEFAULT_EXECUTION,
            temperature: DEFAULT_TEMPERATURE,
            placement: DEFAULT_PLACEMENT,
            current: '380В, 50Гц, трехфазный',
            trials: '',
            movements: 'от 1 до 100',
            speed: '',
            stability: 'до 9 баллов',
            management: '',
            motor: '',
            components: '',
            image:'trolleys-suspension.jpg',
            options: 'радиоуправление; термозащита на электродвигателях; частотное управление; тормоз электродвигателя на передвижение крана;',
            certificate: 'sertificate-mostovoi.pdf',
            seo_descrip: '',
            seo_keyword: ''
        }
    ])

    return {
        cranes
    }
    
})